version: "3.2"
services:
  database:
    container_name: database
    image: postgres:13
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - admin_net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  cache:
    container_name: cache
    image: redis:6
    networks:
      - admin_net

  admin-dashboard:
    container_name: admin-dashboard
    image: directus/directus:latest
    volumes:
      # By default, Directus images writes uploads to /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - admin_net
    depends_on:
      - cache
      - database
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_STORE: ${CACHE_STORE}
      CACHE_REDIS: ${CACHE_REDIS}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      PUBLIC_URL: ${PUBLIC_URL}

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

networks:
  admin_net:

volumes:
  caddy_data:
  caddy_config:
